# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20170704_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField()),
                ('coarse', models.CharField(max_length=200)),
                ('description', models.TextField(default='Good student')),
                ('registration_date', models.DateField(default=datetime.date(2017, 1, 1))),
                ('graduation_date', models.DateField(default=datetime.date(2017, 12, 1))),
            ],
        ),
    ]
